apiVersion: v1
kind: Secret
metadata:
  name: wedding-auth-secrets
type: Opaque
stringData:
  STORAGE_ACCESS_KEY: "ROOTUSER"
  STORAGE_SECRET_KEY: "CHANGEME123"
  FLASK_SECRET_KEY: "super-secure-production-fallback-key"
