apiVersion: v1
kind: Secret
metadata:
  name: wedding-auth-secrets
type: Opaque
stringData:
  GUEST_PASSWORD: "GuestPassword123"
  ADMIN_PASSWORD: "AdminPassword123"
  STORAGE_ACCESS_KEY: "ROOTUSER"
  STORAGE_SECRET_KEY: "CHANGEME123"
